FROM python:3.5.2-slim

RUN apt-get update && apt-get install git -qqy
# add requirements from requirements.txt and all functions here
RUN pip install coverage coveralls

WORKDIR /home

COPY functions /home/functions
COPY tests/unit /home/tests

# unit_test_coverage will check out the master and run a coverage analysis
COPY unit_test_coverage.sh /home
RUN chmod +x unit_test_coverage.sh